### ISSUE TITLE
scarry analytics?

### ISSUE THREAD

**Issue by Darin755** [hello-smile6/libv86-terminal-forwarding#8]
It seems that there is a lot of data collection. I don't enjoy being spied on and it would be nice to have some explanation as to why.

**Comment by hello-smile6** [comment]
> It seems that there is a lot of data collection. I don't enjoy being spied on and it would be nice to have some explanation as to why.

I have analytics so I know how low-quality this is.

**Comment by Darin755** [comment]
With all due respect to you, I will pass

**Comment by hello-smile6** [comment]
> With all due respect to you, I will pass

Go ahead. If you change your mind, throw this in your uBlock Origin-compatible filter list.
```
@@||counter.dev^
```

**Comment by Darin755** [comment]
Fair enough
